### ISSUE TITLE
Released on Spigot? built for EssentialsX?

### ISSUE THREAD

**Issue by pale2hall** [wherkamp/DynmapEssentials#2]
I'm looking for this functionality.

1) is your plugin released on the spigot plugin site?

2) is this compatible with EssentialsX?

**Comment by wherkamp** [comment]
https://www.spigotmc.org/resources/dynmapessentials.87121/
Yes, it was built with EssentialsX.

**Comment by wherkamp** [comment]
Closing this. Feel free to reopen if you have an issue.

**Comment by pale2hall** [comment]
Awesome, I'll give it a shot, TY.

BTW the DL link on SpigotMC.org is broken.
